// bdf2h: BDF bitmap font -> column-major C table, the font5x7.h layout.
//
//	go run bdf2h.go NAME FIRST LAST TOP ROWS < font.bdf > fontNAME.h
//
// Emits `static const uint16_t NAME[LAST-FIRST+1][cell width]`, one uint16
// per glyph column, bit 0 = the topmost kept row. Rows TOP .. TOP+ROWS-1 of
// the font's cell are kept (the X.Org 6x13 keeps 2..12: cap tops at 0,
// baseline after row 9, two descender rows). Glyphs are placed in the cell
// from their BBX like a BDF renderer would; the cell is the FONTBOUNDINGBOX.
// Single file, standard library only: the Makefile runs it with `go run`.
package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type glyph struct {
	w, h, x, y int // BBX
	rows       []uint64
}

func atoi(s string) int {
	v, err := strconv.ParseInt(s, 0, 32)
	if err != nil {
		fmt.Fprintln(os.Stderr, "bdf2h:", err)
		os.Exit(2)
	}
	return int(v)
}

func main() {
	if len(os.Args) != 6 {
		fmt.Fprintln(os.Stderr, "usage: bdf2h NAME FIRST LAST TOP ROWS < font.bdf")
		os.Exit(2)
	}
	name, first, last, top, rows := os.Args[1], atoi(os.Args[2]), atoi(os.Args[3]), atoi(os.Args[4]), atoi(os.Args[5])

	cellW, cellH, ascent := -1, -1, -1
	copyright := ""
	glyphs := map[int]glyph{}
	sc := bufio.NewScanner(os.Stdin)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	var g glyph
	enc, inBitmap := -1, false
	for sc.Scan() {
		f := strings.Fields(sc.Text())
		if len(f) == 0 {
			continue
		}
		switch {
		case inBitmap && f[0] == "ENDCHAR":
			inBitmap = false
			if first <= enc && enc <= last {
				glyphs[enc] = g
			}
		case inBitmap:
			v, err := strconv.ParseUint(f[0], 16, 64)
			if err != nil {
				fmt.Fprintln(os.Stderr, "bdf2h: bad bitmap row:", f[0])
				os.Exit(2)
			}
			g.rows = append(g.rows, v)
		case f[0] == "FONTBOUNDINGBOX":
			cellW, cellH = atoi(f[1]), atoi(f[2])
		case f[0] == "FONT_ASCENT":
			ascent = atoi(f[1])
		case f[0] == "COPYRIGHT":
			copyright = strings.Trim(strings.TrimPrefix(sc.Text(), "COPYRIGHT "), "\" ")
		case f[0] == "STARTCHAR":
			g, enc = glyph{}, -1
		case f[0] == "ENCODING":
			enc = atoi(f[1])
		case f[0] == "BBX":
			g.w, g.h, g.x, g.y = atoi(f[1]), atoi(f[2]), atoi(f[3]), atoi(f[4])
		case f[0] == "BITMAP":
			inBitmap = true
		}
	}
	if cellW < 0 || cellH < 0 || ascent < 0 {
		fmt.Fprintln(os.Stderr, "bdf2h: no FONTBOUNDINGBOX / FONT_ASCENT")
		os.Exit(2)
	}

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprintf(w, "#pragma once\n\n")
	fmt.Fprintf(w, "// GENERATED by bdf2h.go from the X.Org misc %s BDF -- do not edit.\n", strings.TrimPrefix(name, "font"))
	fmt.Fprintf(w, "// BDF COPYRIGHT: \"%s\"\n", copyright)
	fmt.Fprintf(w, "// Column-major, ASCII 0x%02X..0x%02X, %d columns per glyph (the cell width,\n", first, last, cellW)
	fmt.Fprintf(w, "// no gap added by the renderer), bit 0 = top; cell rows %d..%d kept.\n\n", top, top+rows-1)
	fmt.Fprintf(w, "#include <stdint.h>\n\n")
	fmt.Fprintf(w, "static const uint16_t %s[%d][%d] = {\n", name, last-first+1, cellW)
	for enc := first; enc <= last; enc++ {
		cols := make([]uint16, cellW)
		if g, ok := glyphs[enc]; ok {
			nbits := (g.w + 7) / 8 * 8 // bitmap rows are byte-padded, MSB = leftmost
			for r, word := range g.rows {
				y := ascent - g.y - g.h + r - top // cell row of this bitmap row, cropped
				if y < 0 || y >= rows {
					continue
				}
				for c := 0; c < g.w; c++ {
					if word>>(nbits-1-c)&1 != 0 && g.x+c >= 0 && g.x+c < cellW {
						cols[g.x+c] |= 1 << y
					}
				}
			}
		}
		label := fmt.Sprintf("'%c'", enc)
		switch enc {
		case '\'':
			label = `'\''`
		case '\\':
			label = `'\\'`
		}
		fmt.Fprintf(w, "    {")
		for i, v := range cols {
			if i > 0 {
				fmt.Fprintf(w, ", ")
			}
			fmt.Fprintf(w, "0x%04X", v)
		}
		fmt.Fprintf(w, "}, // %s\n", label)
	}
	fmt.Fprintf(w, "};\n")
}
